"""Generate OSI-aware archetype schemas consumed by the frontend asset modal."""

from typing import Dict, List, TypedDict

from src.core.constants import (
    ARCHETYPE_DESCRIPTIONS,
    ARCHETYPE_LABELS,
    AssetArchetype,
    LAYER_ARCHETYPES,
    LAYER_METADATA,
    OPTIONAL_SECONDARY_LAYERS,
    Provider,
)
from src.core.models import PermissionPreset


class FieldSpec(TypedDict, total=False):
    name: str
    label: str
    helper_text: str | None
    placeholder: str | None
    validation_hint: str | None
    example: str | None
    required: bool
    field_type: str


class ArchetypeSchema(TypedDict):
    archetype: AssetArchetype
    label: str
    description: str
    providers: List[str]
    provider_other_requires_name: bool
    fields: List[FieldSpec]
    defaults: Dict[str, str | List[str]]
    connection_requirements: List[str]
    optional_secondary_layers: List[str] | None


_ALL_PROVIDERS = [provider.value for provider in Provider]

_FIELD_LIBRARY: Dict[str, FieldSpec] = {
    "display_name": {
        "label": "Asset name",
        "helper_text": "Unique, human-friendly name for the asset.",
        "placeholder": "e.g., AWS prod org",
        "required": True,
        "field_type": "string",
    },
    "provider_account_id": {
        "label": "Cloud account identifier",
        "helper_text": "e.g., AWS account ID, Azure tenant, or GCP project.",
        "placeholder": "123456789012",
        "validation_hint": "12 digits (AWS) / tenant/project id",
        "example": "375922117580",
        "required": True,
        "field_type": "string",
    },
    "provider_resource_id": {
        "label": "Resource identifier",
        "helper_text": "Native identifier (ARN, name, ID) for the resource.",
        "placeholder": "vpc-12345 / lb-abc / bucket-name",
        "required": False,
        "field_type": "string",
    },
    "permission_preset": {
        "label": "Permission preset",
        "helper_text": "Least-privileged preset applied during onboarding.",
        "placeholder": "SECURITY_READONLY",
        "required": False,
        "field_type": "select",
    },
    "auth_method": {
        "label": "Access method",
        "helper_text": "How Risklence authenticates (e.g., role, service principal).",
        "placeholder": "CROSS_ACCOUNT_ROLE / SERVICE_PRINCIPAL / OIDC",
        "required": False,
        "field_type": "string",
    },
}


_ARCHETYPE_BLUEPRINTS: Dict[AssetArchetype, Dict[str, List[str] | Dict[str, str | List[str]]]] = {
    AssetArchetype.CLOUD_ACCOUNT_GOVERNANCE: {
        "required": ["display_name", "provider_account_id"],
        "optional": ["permission_preset", "auth_method"],
        "providers": _ALL_PROVIDERS,
        "connection_requirements": [
            "external_id generated by Risklence",
            "Role ARN saved via complete setup",
        ],
        "defaults": {
            "permission_preset": PermissionPreset.SECURITY_READONLY.value,
            "intent_suggestions": ["SECURITY_MONITORING", "COMPLIANCE"],
            "scan_start_mode": "AFTER_SME_CONFIRM",
        },
    },
    AssetArchetype.IDENTITY_PROVIDER: {
        "required": ["display_name"],
        "optional": ["provider_resource_id"],
        "providers": _ALL_PROVIDERS,
        "connection_requirements": ["Provider metadata + connection instructions"],
        "defaults": {
            "intent_suggestions": ["SECURITY_MONITORING", "AUDIT_EVIDENCE"],
        },
    },
    AssetArchetype.POLICY_ENGINE: {
        "required": ["display_name"],
        "optional": ["provider_resource_id"],
        "providers": _ALL_PROVIDERS,
        "connection_requirements": ["Policy engine API credentials (future)"],
        "defaults": {
            "intent_suggestions": ["DRIFT_DETECTION", "COMPLIANCE"],
        },
    },
    AssetArchetype.CLOUD_NETWORK_SEGMENT: {
        "required": ["display_name", "provider_resource_id"],
        "optional": [],
        "providers": _ALL_PROVIDERS,
        "connection_requirements": ["Linked governance account"],
        "defaults": {
            "intent_suggestions": ["SECURITY_MONITORING"],
        },
    },
    AssetArchetype.PERIMETER_FIREWALL: {
        "required": ["display_name", "provider_resource_id"],
        "optional": [],
        "providers": _ALL_PROVIDERS,
        "connection_requirements": ["Linked governance account"],
        "defaults": {
            "intent_suggestions": ["SECURITY_MONITORING"],
        },
    },
    AssetArchetype.LOAD_BALANCER_INGRESS: {
        "required": ["display_name", "provider_resource_id"],
        "optional": [],
        "providers": _ALL_PROVIDERS,
        "connection_requirements": ["Linked governance account"],
        "defaults": {
            "intent_suggestions": ["AUDIT_EVIDENCE"],
        },
    },
    AssetArchetype.CONTAINER_PLATFORM: {
        "required": ["display_name", "provider_resource_id"],
        "optional": ["permission_preset"],
        "providers": _ALL_PROVIDERS,
        "connection_requirements": ["Governance account relationship"],
        "defaults": {
            "permission_preset": PermissionPreset.SECURITY_READONLY.value,
            "intent_suggestions": ["DRIFT_DETECTION"],
        },
    },
    AssetArchetype.APPLICATION_SERVICE: {
        "required": ["display_name", "provider_resource_id"],
        "optional": [],
        "providers": _ALL_PROVIDERS,
        "connection_requirements": ["Governance account relationship"],
        "defaults": {
            "intent_suggestions": ["SECURITY_MONITORING"],
        },
    },
    AssetArchetype.OBJECT_STORAGE: {
        "required": ["display_name", "provider_resource_id"],
        "optional": ["permission_preset"],
        "providers": _ALL_PROVIDERS,
        "connection_requirements": ["Governance account relationship"],
        "defaults": {
            "permission_preset": PermissionPreset.SECURITY_READONLY.value,
            "intent_suggestions": ["COMPLIANCE"],
        },
    },
    AssetArchetype.RELATIONAL_DATABASE: {
        "required": ["display_name", "provider_resource_id"],
        "optional": ["permission_preset"],
        "providers": _ALL_PROVIDERS,
        "connection_requirements": ["Governance account relationship"],
        "defaults": {
            "permission_preset": PermissionPreset.SECURITY_READONLY.value,
            "intent_suggestions": ["AUDIT_EVIDENCE"],
        },
    },
}


def _make_field(name: str, required: bool) -> FieldSpec:
    template = _FIELD_LIBRARY.get(name, {})
    return {**template, "name": name, "required": required}


def _build_field_list(names: List[str], required: bool) -> List[FieldSpec]:
    return [_make_field(name, required) for name in names]


def get_archetype_schemas_for_layer(layer: str) -> List[ArchetypeSchema]:
    """Return archetype schemas for the requested OSI layer."""
    allowed = LAYER_ARCHETYPES.get(layer, [])
    schemas: List[ArchetypeSchema] = []

    for archetype in allowed:
        blueprint = _ARCHETYPE_BLUEPRINTS.get(archetype, {})
        required = blueprint.get("required", [])
        optional = blueprint.get("optional", [])
        schemas.append(
            ArchetypeSchema(
                archetype=archetype,
                label=ARCHETYPE_LABELS.get(archetype, archetype.value),
                description=ARCHETYPE_DESCRIPTIONS.get(archetype, ""),
                providers=blueprint.get("providers", _ALL_PROVIDERS),  # type: ignore[arg-type]
                provider_other_requires_name=True,
                fields=_build_field_list(required, True) + _build_field_list(optional, False),
                defaults=blueprint.get("defaults", {}),
                connection_requirements=blueprint.get("connection_requirements", []),
                optional_secondary_layers=OPTIONAL_SECONDARY_LAYERS.get(archetype),
            )
        )
    return schemas


def get_layer_label_and_description(layer: str) -> tuple[str, str] | None:
    meta = next((entry for entry in LAYER_METADATA if entry["id"] == layer), None)
    if not meta:
        return None
    return f"{layer} — {meta['label']}", meta["description"]
