"""Shared constants for recommendation, decision, and resolution runtime flows."""

DECISION_ACTION_JIRA = "jira"
DECISION_ACTION_SERVICENOW = "servicenow"
DECISION_ACTION_ACCEPTED = "accepted"
DECISION_ACTION_ESCALATED = "escalated"

DECISION_ACTIONS = (
    DECISION_ACTION_JIRA,
    DECISION_ACTION_SERVICENOW,
    DECISION_ACTION_ACCEPTED,
    DECISION_ACTION_ESCALATED,
)

ACTIONABLE_DECISION_ACTIONS = (
    DECISION_ACTION_JIRA,
    DECISION_ACTION_SERVICENOW,
    DECISION_ACTION_ESCALATED,
)

DECISION_TYPE_RECOMMENDED = "recommended"
DECISION_TYPE_ALTERNATIVE = "alternative"

BUSINESS_DECISION_ACTION_ACCEPT = "accept"
BUSINESS_DECISION_ACTION_MITIGATE = "mitigate"
BUSINESS_DECISION_ACTION_DEFER = "defer"
BUSINESS_DECISION_ACTION_REJECT = "reject"

BUSINESS_DECISION_ACTIONS = (
    BUSINESS_DECISION_ACTION_ACCEPT,
    BUSINESS_DECISION_ACTION_MITIGATE,
    BUSINESS_DECISION_ACTION_DEFER,
    BUSINESS_DECISION_ACTION_REJECT,
)

DECISION_ROUTE_TO_BUSINESS_ACTION = {
    DECISION_ACTION_JIRA: BUSINESS_DECISION_ACTION_MITIGATE,
    DECISION_ACTION_SERVICENOW: BUSINESS_DECISION_ACTION_MITIGATE,
    DECISION_ACTION_ACCEPTED: BUSINESS_DECISION_ACTION_ACCEPT,
    DECISION_ACTION_ESCALATED: BUSINESS_DECISION_ACTION_DEFER,
}

RECOMMENDATION_STATUS_OPEN = "open"
RECOMMENDATION_STATUS_DECIDED = "decided"

RECOMMENDATION_TYPE_RUNTIME_THREAT = "runtime_threat"
RECOMMENDATION_TYPE_CRITICAL_ASSET = "critical_asset"

RECOMMENDATION_GENERATOR_VERSION = "euc-11-v1"

THREAT_STATUS_ACCEPTED = "accepted"
THREAT_STATUS_IN_PROGRESS = "in-progress"
THREAT_STATUS_KEPT_SAFE = "kept-safe"

RESOLUTION_TYPE_FOLLOWED_RECOMMENDATION = "followed-recommendation"
RESOLUTION_TYPE_SOLVED_DIFFERENTLY = "solved-differently"
RESOLUTION_TYPE_ACCEPTED_RISK = "accepted-risk"
RESOLUTION_TYPE_NOT_RESOLVED = "not-resolved"

RESOLUTION_TYPES = (
    RESOLUTION_TYPE_FOLLOWED_RECOMMENDATION,
    RESOLUTION_TYPE_SOLVED_DIFFERENTLY,
    RESOLUTION_TYPE_ACCEPTED_RISK,
    RESOLUTION_TYPE_NOT_RESOLVED,
)

ALTERNATIVE_RESOLUTION_CATEGORY_ADDED_FALLBACK = "added_fallback"
ALTERNATIVE_RESOLUTION_CATEGORY_REPLACED_PROVIDER = "replaced_provider"
ALTERNATIVE_RESOLUTION_CATEGORY_CHANGED_ARCHITECTURE = "changed_architecture"
ALTERNATIVE_RESOLUTION_CATEGORY_PROCESS_CHANGE = "process_change"
ALTERNATIVE_RESOLUTION_CATEGORY_OTHER = "other"

ALTERNATIVE_RESOLUTION_CATEGORIES = (
    ALTERNATIVE_RESOLUTION_CATEGORY_ADDED_FALLBACK,
    ALTERNATIVE_RESOLUTION_CATEGORY_REPLACED_PROVIDER,
    ALTERNATIVE_RESOLUTION_CATEGORY_CHANGED_ARCHITECTURE,
    ALTERNATIVE_RESOLUTION_CATEGORY_PROCESS_CHANGE,
    ALTERNATIVE_RESOLUTION_CATEGORY_OTHER,
)

RESOLUTION_STATUS_CAPTURED = "captured"
VERIFICATION_STATUS_PENDING = "pending"
VERIFICATION_STATUS_SUCCESSFUL = "verified_successful"
VERIFICATION_STATUS_ALTERNATIVE = "verified_alternative"
VERIFICATION_STATUS_INSUFFICIENT = "verified_insufficient"
VERIFICATION_STATUS_NOT_VERIFIED = "not_verified"

VERIFICATION_STATUSES = (
    VERIFICATION_STATUS_PENDING,
    VERIFICATION_STATUS_SUCCESSFUL,
    VERIFICATION_STATUS_ALTERNATIVE,
    VERIFICATION_STATUS_INSUFFICIENT,
    VERIFICATION_STATUS_NOT_VERIFIED,
)
