"""Shared constants for learning-loop signals, runs, and candidate governance."""

RUN_STATUS_RUNNING = "running"
RUN_STATUS_COMPLETED = "completed"
RUN_STATUS_FAILED = "failed"

TRIGGERED_BY_MANUAL = "manual"
TRIGGERED_BY_SCHEDULED = "scheduled"

TRAINING_SIGNAL_SOURCE_MAPPING_DECISION = "mapping_decision"
TRAINING_SIGNAL_SOURCE_DECISION_RECORD = "decision_record"
TRAINING_SIGNAL_SOURCE_RESOLUTION_RECORD = "resolution_record"
TRAINING_SIGNAL_SOURCE_VERIFICATION_RECORD = "verification_record"
TRAINING_SIGNAL_SOURCE_RECOMMENDATION = "recommendation"

TRAINING_SIGNAL_SOURCES = (
    TRAINING_SIGNAL_SOURCE_MAPPING_DECISION,
    TRAINING_SIGNAL_SOURCE_DECISION_RECORD,
    TRAINING_SIGNAL_SOURCE_RESOLUTION_RECORD,
    TRAINING_SIGNAL_SOURCE_VERIFICATION_RECORD,
    TRAINING_SIGNAL_SOURCE_RECOMMENDATION,
)

SIGNAL_TYPE_TEMPLATE_PATTERN = "template_pattern_feedback"
SIGNAL_TYPE_RECOMMENDATION_DECISION = "recommendation_decision_feedback"
SIGNAL_TYPE_RESOLUTION_OUTCOME = "resolution_outcome_feedback"
SIGNAL_TYPE_VERIFICATION_OUTCOME = "verification_outcome_feedback"
SIGNAL_TYPE_RECOMMENDATION_GENERATION = "recommendation_generation_feedback"

TRAINING_SIGNAL_TYPES = (
    SIGNAL_TYPE_TEMPLATE_PATTERN,
    SIGNAL_TYPE_RECOMMENDATION_DECISION,
    SIGNAL_TYPE_RESOLUTION_OUTCOME,
    SIGNAL_TYPE_VERIFICATION_OUTCOME,
    SIGNAL_TYPE_RECOMMENDATION_GENERATION,
)

CANDIDATE_TYPE_TEMPLATE_PATTERN = "template_pattern_adjustment"
CANDIDATE_TYPE_RECOMMENDATION_RANKING = "recommendation_ranking_adjustment"
CANDIDATE_TYPE_RESOLUTION_GUIDANCE = "resolution_guidance_adjustment"

LEARNING_CANDIDATE_TYPES = (
    CANDIDATE_TYPE_TEMPLATE_PATTERN,
    CANDIDATE_TYPE_RECOMMENDATION_RANKING,
    CANDIDATE_TYPE_RESOLUTION_GUIDANCE,
)

TARGET_TYPE_SERVICE_TEMPLATE_GROUP = "service_template_group"
TARGET_TYPE_RECOMMENDATION_ACTION = "recommendation_action"
TARGET_TYPE_RESOLUTION_ACTION = "resolution_action"
TARGET_TYPE_RECOMMENDATION_CONTEXT = "recommendation_context"

RECOMMENDATION_SIGNAL_OUTCOME_GENERATED = "recommendation_generated"
RECOMMENDATION_SIGNAL_OUTCOME_UNCERTAINTY_FLAGGED = "recommendation_uncertainty_flagged"
RECOMMENDATION_SIGNAL_OUTCOME_CONTEXT_REFRESHED = "recommendation_context_refreshed"

GOVERNANCE_CLASS_A = "A"
GOVERNANCE_CLASS_B = "B"
GOVERNANCE_CLASS_C = "C"

GOVERNANCE_CLASSES = (
    GOVERNANCE_CLASS_A,
    GOVERNANCE_CLASS_B,
    GOVERNANCE_CLASS_C,
)

CANDIDATE_STATUS_PENDING = "pending"
CANDIDATE_STATUS_AUTO_STAGED = "auto_staged"
CANDIDATE_STATUS_APPROVED = "approved"
CANDIDATE_STATUS_REJECTED = "rejected"

LEARNING_CANDIDATE_STATUSES = (
    CANDIDATE_STATUS_PENDING,
    CANDIDATE_STATUS_AUTO_STAGED,
    CANDIDATE_STATUS_APPROVED,
    CANDIDATE_STATUS_REJECTED,
)
