from __future__ import annotations

from typing import Any

from src.core.constants.decision_runtime import (
    DECISION_ACTION_ACCEPTED,
    DECISION_ACTION_ESCALATED,
    DECISION_ACTION_JIRA,
    DECISION_TYPE_RECOMMENDED,
)

WEAKNESS_BLUEPRINTS: list[dict[str, Any]] = [
    {
        "key": "cloudflare_single_provider_dependency",
        "dependency": "Cloudflare Platform",
        "asset": "Cloudflare Edge Hosting",
        "title": "Full dependency on Cloudflare with no failover path",
        "business_impact": "A Cloudflare outage would immediately affect customer entry points and security controls.",
        "recommendation": "Add an alternate ingress path and document a DNS cutover procedure for emergency use.",
        "severity": "high",
        "recommended_action": DECISION_ACTION_ACCEPTED,
    },
    {
        "key": "database_single_instance",
        "dependency": "PostgreSQL Database",
        "asset": "Managed PostgreSQL",
        "title": "Single point of failure in the database tier",
        "business_impact": "A database failure would stop core SaaS operations, billing, and access control.",
        "recommendation": "Introduce a standby replica and automate failover testing.",
        "severity": "critical",
        "recommended_action": DECISION_ACTION_JIRA,
    },
    {
        "key": "no_database_backup",
        "dependency": "PostgreSQL Database",
        "asset": "Managed PostgreSQL",
        "title": "No backup strategy defined for the primary database",
        "business_impact": "Recovery from data corruption or deletion would be slow and potentially incomplete.",
        "recommendation": "Implement daily backups with periodic restore tests and retention policy.",
        "severity": "high",
        "recommended_action": DECISION_ACTION_JIRA,
    },
    {
        "key": "no_multi_region_failover",
        "dependency": "DigitalOcean Platform",
        "asset": "App Platform (API)",
        "title": "No multi-region failover for the application platform",
        "business_impact": "A regional outage would take the API path offline and impact customer operations.",
        "recommendation": "Add a second region and define traffic failover rules for the platform layer.",
        "severity": "high",
        "recommended_action": DECISION_ACTION_JIRA,
    },
    {
        "key": "auth_no_degraded_mode",
        "dependency": "Auth Service",
        "asset": "Auth Service",
        "title": "Authentication has no degraded mode",
        "business_impact": "If identity services degrade, users cannot sign in or recover access.",
        "recommendation": "Define break-glass access and a read-only degraded authentication path.",
        "severity": "medium",
        "recommended_action": DECISION_ACTION_ACCEPTED,
    },
    {
        "key": "cicd_direct_to_prod",
        "dependency": "CI/CD Pipeline",
        "asset": "CI/CD Pipeline",
        "title": "CI/CD can deploy directly to production",
        "business_impact": "A flawed release can reach production without human review or rollback preparation.",
        "recommendation": "Require staged promotion and mandatory approval for production deploys.",
        "severity": "high",
        "recommended_action": DECISION_ACTION_ESCALATED,
    },
    {
        "key": "cicd_no_rollback",
        "dependency": "CI/CD Pipeline",
        "asset": "CI/CD Pipeline",
        "title": "No rollback strategy is defined for production releases",
        "business_impact": "Recovering from a failed deployment would depend on manual hotfixes only.",
        "recommendation": "Add versioned release artifacts and automated rollback steps to the pipeline.",
        "severity": "medium",
        "recommended_action": DECISION_ACTION_JIRA,
    },
    {
        "key": "single_region_deployment",
        "dependency": "DigitalOcean Platform",
        "asset": "App Platform (SCORM service)",
        "title": "Single region deployment on DigitalOcean",
        "business_impact": "A regional provider issue would affect the platform with no failover region ready.",
        "recommendation": "Distribute workloads across at least two regions and test failover quarterly.",
        "severity": "high",
        "recommended_action": DECISION_ACTION_JIRA,
    },
]

DECISION_BLUEPRINTS: list[dict[str, Any]] = [
    {
        "intervention_key": "cloudflare_single_provider_dependency",
        "selected_action": DECISION_ACTION_ACCEPTED,
        "decision_type": DECISION_TYPE_RECOMMENDED,
        "decided_by": "Risklence Admin",
        "decided_role": "admin",
        "timestamp": "2026-04-30 09:15",
        "review_date": "2026-05-30",
        "ref": None,
        "integration_provider": None,
        "rationale": "Cloudflare remains acceptable for the current footprint while the team records a cutover runbook.",
    },
    {
        "intervention_key": "auth_no_degraded_mode",
        "selected_action": DECISION_ACTION_ACCEPTED,
        "decision_type": DECISION_TYPE_RECOMMENDED,
        "decided_by": "Risklence Admin",
        "decided_role": "admin",
        "timestamp": "2026-04-30 09:20",
        "review_date": "2026-05-30",
        "ref": None,
        "integration_provider": None,
        "rationale": "Accept the temporary limitation while the break-glass flow is documented.",
    },
    {
        "intervention_key": "database_single_instance",
        "selected_action": DECISION_ACTION_JIRA,
        "decision_type": DECISION_TYPE_RECOMMENDED,
        "decided_by": "Risklence Admin",
        "decided_role": "admin",
        "timestamp": "2026-04-30 09:25",
        "review_date": None,
        "ref": "JR-4101",
        "integration_provider": "jira",
        "rationale": "Raised JR-4101 to add a standby replica and validate failover.",
    },
    {
        "intervention_key": "no_multi_region_failover",
        "selected_action": DECISION_ACTION_JIRA,
        "decision_type": DECISION_TYPE_RECOMMENDED,
        "decided_by": "Risklence Admin",
        "decided_role": "admin",
        "timestamp": "2026-04-30 09:30",
        "review_date": None,
        "ref": "JR-4102",
        "integration_provider": "jira",
        "rationale": "Raised JR-4102 to add a second region and document traffic failover.",
    },
    {
        "intervention_key": "cicd_direct_to_prod",
        "selected_action": DECISION_ACTION_ESCALATED,
        "decision_type": DECISION_TYPE_RECOMMENDED,
        "decided_by": "Risklence Admin",
        "decided_role": "admin",
        "timestamp": "2026-04-30 09:35",
        "review_date": None,
        "ref": "INV-4103",
        "integration_provider": "risklence",
        "rationale": "Escalate the production-deploy risk for a design review before changing the pipeline.",
    },
]
