from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from src.core.model_defs.assets_runtime import AssetStatus, ConnectivityStatus, Criticality
from src.core.constants import SERVICE_TIER_BUSINESS_CRITICAL, SERVICE_TIER_MISSION_CRITICAL

ORGANIZATION_SLUG = "risklence-internal"
ORGANIZATION_NAME = "Risklence"
# Deterministic development-only registration identifier. It is deliberately
# fictional and gives the authenticated identity flow the same shape as a
# tenant activated from CVR data, without representing a real company record.
MOCK_CVR_NUMBER = "99990007"
FIXTURE_TIMESTAMP = datetime(2026, 4, 30, 9, 0, tzinfo=timezone.utc)
FIXTURE_TIMESTAMP_LATER = datetime(2026, 4, 30, 11, 15, tzinfo=timezone.utc)

BUSINESS_PROCESS_BLUEPRINTS: list[dict[str, Any]] = [
    {
        "key": "software_delivery",
        "name": "SaaS Core Platform",
        "library_item_id": "software_delivery",
        "priority": "critical",
        "source": "inferred",
        "services": [
            "API Platform",
            "Frontend Application",
            "Authentication & Access",
            "Data Platform",
        ],
    },
    {
        "key": "customer_lifecycle",
        "name": "Customer Lifecycle",
        "library_item_id": "customer_service",
        "priority": "important",
        "source": "inferred",
        "services": ["Customer Onboarding", "Billing & Subscription Management"],
    },
    {
        "key": "billing_subscription",
        "name": "Billing & Subscription",
        "library_item_id": "contract_to_renewal",
        "priority": "critical",
        "source": "inferred",
        "services": ["Billing & Subscription Management"],
    },
]

SERVICE_BLUEPRINTS: list[dict[str, Any]] = [
    {
        "name": "API Platform",
        "service_key": "application_service",
        "template_key": "application_service",
        "archetype": "customer_channel",
        "tier": SERVICE_TIER_MISSION_CRITICAL,
        "tolerance_window": "le_4h",
        "suggested_mtd_hours": 2,
        "validated_mtd_hours": 2,
        "value_stream_keys": ["software_delivery"],
        "trading_impact": "API downtime blocks paid customer traffic, renewals, and integrations. Estimated exposure 1.2m per day.",
        "dependencies": [
            "API Service",
            "App Platform (API)",
            "Managed PostgreSQL",
            "CI/CD Pipeline",
            "Engineering Team",
        ],
    },
    {
        "name": "Frontend Application",
        "service_key": "web_channel",
        "template_key": "web_channel",
        "archetype": "customer_channel",
        "tier": SERVICE_TIER_MISSION_CRITICAL,
        "tolerance_window": "le_4h",
        "suggested_mtd_hours": 2,
        "validated_mtd_hours": 2,
        "value_stream_keys": ["software_delivery"],
        "trading_impact": "Customer portal outage stops acquisition and support. Estimated exposure 800k per day.",
        "dependencies": [
            "Frontend App",
            "Cloudflare DNS",
            "Cloudflare Edge Hosting",
            "Cloudflare WAF",
            "Engineering Team",
        ],
    },
    {
        "name": "Authentication & Access",
        "service_key": "identity_service",
        "template_key": "identity_service",
        "archetype": "identity_access",
        "tier": SERVICE_TIER_MISSION_CRITICAL,
        "tolerance_window": "le_4h",
        "suggested_mtd_hours": 2,
        "validated_mtd_hours": 2,
        "value_stream_keys": ["software_delivery"],
        "trading_impact": "Login failures block tenant and admin access across the platform. Estimated exposure 600k per day.",
        "dependencies": ["Auth Service", "Managed PostgreSQL", "Engineering Team"],
    },
    {
        "name": "Data Platform",
        "service_key": "data_warehouse",
        "template_key": "data_warehouse",
        "archetype": "data_store",
        "tier": SERVICE_TIER_MISSION_CRITICAL,
        "tolerance_window": "le_4h",
        "suggested_mtd_hours": 4,
        "validated_mtd_hours": 4,
        "value_stream_keys": ["software_delivery", "billing_subscription"],
        "trading_impact": "Reporting and billing datasets delay invoicing and operations reporting. Estimated exposure 700k per day.",
        "dependencies": ["Managed PostgreSQL", "App Platform (SCORM service)", "Engineering Team"],
    },
    {
        "name": "Customer Onboarding",
        "service_key": "onboarding_service",
        "template_key": "onboarding_service",
        "archetype": "support_service",
        "tier": SERVICE_TIER_BUSINESS_CRITICAL,
        "tolerance_window": "le_4h",
        "suggested_mtd_hours": 1,
        "validated_mtd_hours": 4,
        "value_stream_keys": ["customer_lifecycle"],
        "trading_impact": "Delayed activation extends time-to-value and slows conversion. Estimated exposure 250k per day.",
        "dependencies": ["Frontend App", "API Service", "Auth Service", "Engineering Team"],
    },
    {
        "name": "Billing & Subscription Management",
        "service_key": "billing_service",
        "template_key": "billing_service",
        "archetype": "transactional_system",
        "tier": SERVICE_TIER_BUSINESS_CRITICAL,
        "tolerance_window": "gt_24h",
        "suggested_mtd_hours": 24,
        "validated_mtd_hours": 48,
        "value_stream_keys": ["customer_lifecycle", "billing_subscription"],
        "trading_impact": "Billing failures delay invoicing and renewals. Estimated exposure 900k per day.",
        "dependencies": ["API Service", "Managed PostgreSQL", "CI/CD Pipeline", "Engineering Team"],
    },
]

DEPENDENCY_BLUEPRINTS: list[dict[str, Any]] = [
    {"name": "API Service", "category": "application", "asset_names": ["API Service"]},
    {"name": "Frontend App", "category": "application", "asset_names": ["Frontend App"]},
    {"name": "Auth Service", "category": "application", "asset_names": ["Auth Service"]},
    {
        "name": "Cloudflare Platform",
        "category": "infrastructure",
        "asset_names": ["Cloudflare DNS", "Cloudflare Edge Hosting", "Cloudflare WAF"],
    },
    {
        "name": "DigitalOcean Platform",
        "category": "infrastructure",
        "asset_names": ["App Platform (API)", "App Platform (SCORM service)", "Managed PostgreSQL"],
    },
    {
        "name": "PostgreSQL Database",
        "category": "infrastructure",
        "asset_names": ["Managed PostgreSQL"],
    },
    {"name": "Engineering Team", "category": "operations", "asset_names": ["Engineering Team"]},
    {"name": "CI/CD Pipeline", "category": "operations", "asset_names": ["CI/CD Pipeline"]},
]

ASSET_BLUEPRINTS: list[dict[str, Any]] = [
    {
        "display_name": "API Service",
        "provider": "Risklence",
        "provider_display_name": "Risklence",
        "type": "Application",
        "layer": "Application",
        "criticality": Criticality.CRITICAL,
        "status": AssetStatus.PARTIALLY_OBSERVED,
        "connectivity_status": ConnectivityStatus.CONNECTED,
        "risk_score": 0.78,
        "findings_count": 2,
        "is_spof": True,
        "confidence": 0.87,
    },
    {
        "display_name": "Frontend App",
        "provider": "Risklence",
        "provider_display_name": "Risklence",
        "type": "Application",
        "layer": "Application",
        "criticality": Criticality.HIGH,
        "status": AssetStatus.PARTIALLY_OBSERVED,
        "connectivity_status": ConnectivityStatus.CONNECTED,
        "risk_score": 0.72,
        "findings_count": 1,
        "is_spof": False,
        "confidence": 0.84,
    },
    {
        "display_name": "Auth Service",
        "provider": "Risklence",
        "provider_display_name": "Risklence",
        "type": "Identity Service",
        "layer": "Application",
        "criticality": Criticality.CRITICAL,
        "status": AssetStatus.PARTIALLY_OBSERVED,
        "connectivity_status": ConnectivityStatus.CONNECTED,
        "risk_score": 0.81,
        "findings_count": 2,
        "is_spof": True,
        "confidence": 0.83,
    },
    {
        "display_name": "Engineering Team",
        "provider": "Risklence",
        "provider_display_name": "Risklence",
        "type": "Team",
        "layer": "Operations",
        "criticality": Criticality.HIGH,
        "status": AssetStatus.OPERATIONALLY_COMPLIANT,
        "connectivity_status": ConnectivityStatus.CONNECTED,
        "risk_score": 0.42,
        "findings_count": 0,
        "is_spof": False,
        "confidence": 0.94,
    },
    {
        "display_name": "Cloudflare DNS",
        "provider": "Cloudflare",
        "provider_display_name": "Cloudflare",
        "type": "DNS",
        "layer": "Infrastructure",
        "criticality": Criticality.HIGH,
        "status": AssetStatus.AT_RISK,
        "connectivity_status": ConnectivityStatus.CONNECTED,
        "risk_score": 0.86,
        "findings_count": 1,
        "is_spof": True,
        "confidence": 0.96,
    },
    {
        "display_name": "Cloudflare Edge Hosting",
        "provider": "Cloudflare",
        "provider_display_name": "Cloudflare",
        "type": "Hosting",
        "layer": "Infrastructure",
        "criticality": Criticality.CRITICAL,
        "status": AssetStatus.AT_RISK,
        "connectivity_status": ConnectivityStatus.CONNECTED,
        "risk_score": 0.91,
        "findings_count": 2,
        "is_spof": True,
        "confidence": 0.95,
    },
    {
        "display_name": "Cloudflare WAF",
        "provider": "Cloudflare",
        "provider_display_name": "Cloudflare",
        "type": "WAF",
        "layer": "Infrastructure",
        "criticality": Criticality.HIGH,
        "status": AssetStatus.AT_RISK,
        "connectivity_status": ConnectivityStatus.CONNECTED,
        "risk_score": 0.83,
        "findings_count": 1,
        "is_spof": False,
        "confidence": 0.92,
    },
    {
        "display_name": "App Platform (API)",
        "provider": "DigitalOcean",
        "provider_display_name": "DigitalOcean",
        "type": "App Platform",
        "layer": "Infrastructure",
        "criticality": Criticality.CRITICAL,
        "status": AssetStatus.AT_RISK,
        "connectivity_status": ConnectivityStatus.CONNECTED,
        "risk_score": 0.89,
        "findings_count": 2,
        "is_spof": True,
        "confidence": 0.91,
    },
    {
        "display_name": "App Platform (SCORM service)",
        "provider": "DigitalOcean",
        "provider_display_name": "DigitalOcean",
        "type": "App Platform",
        "layer": "Infrastructure",
        "criticality": Criticality.MEDIUM,
        "status": AssetStatus.AT_RISK,
        "connectivity_status": ConnectivityStatus.CONNECTED,
        "risk_score": 0.63,
        "findings_count": 1,
        "is_spof": False,
        "confidence": 0.78,
    },
    {
        "display_name": "Managed PostgreSQL",
        "provider": "DigitalOcean",
        "provider_display_name": "DigitalOcean",
        "type": "Database",
        "layer": "Data",
        "criticality": Criticality.CRITICAL,
        "status": AssetStatus.AT_RISK,
        "connectivity_status": ConnectivityStatus.DEGRADED,
        "risk_score": 0.97,
        "findings_count": 4,
        "is_spof": True,
        "confidence": 0.97,
    },
    {
        "display_name": "CI/CD Pipeline",
        "provider": "GitHub",
        "provider_display_name": "GitHub Actions",
        "type": "Pipeline",
        "layer": "Operations",
        "criticality": Criticality.HIGH,
        "status": AssetStatus.AT_RISK,
        "connectivity_status": ConnectivityStatus.CONNECTED,
        "risk_score": 0.88,
        "findings_count": 2,
        "is_spof": True,
        "confidence": 0.9,
    },
]


def build_risklence_service_suggestions() -> list[dict[str, Any]]:
    descriptions = [
        "Guided suggestion for the API surface that runs customer transactions and integrations.",
        "Guided suggestion for the web channel that serves the customer-facing application.",
        "Guided suggestion for identity and access control across the tenant.",
        "Guided suggestion for the shared data layer that powers reporting and billing.",
        "Guided suggestion for the onboarding flow that activates a new tenant.",
        "Guided suggestion for billing and subscription operations.",
    ]
    return [
        {
            "name": item["name"],
            "description": description,
            "source": "ai_suggested",
            "confirmed": False,
        }
        for item, description in zip(SERVICE_BLUEPRINTS, descriptions, strict=False)
    ]
