"""
Helpers for normalizing JWT-related secrets.

The login flow signs access tokens with a shared HS256 secret that may be stored
in a Base64-friendly form (for example the value generated by
`scripts/generate_jwt_secret.py`). These helpers centralize the decoding logic so
both the auth service (which signs tokens) and the tenant middleware (which
verifies tokens) work from an identical byte string.
"""

from __future__ import annotations

import base64
import binascii
from typing import Optional, Union

from pydantic import SecretStr

from src.core.config import settings
from src.core.exceptions import ConfigurationError


def _normalize_secret_value(value: Union[str, SecretStr]) -> bytes:
    """Decode a secret that may already be Base64 encoded."""
    raw = value.get_secret_value() if isinstance(value, SecretStr) else value
    trimmed = raw.strip()

    # Try to treat the string as URL-safe Base64.
    padded = trimmed + "=" * ((4 - len(trimmed) % 4) % 4)
    try:
        decoded = base64.urlsafe_b64decode(padded)
        if decoded:
            reencoded = base64.urlsafe_b64encode(decoded).decode("utf-8").rstrip("=")
            if reencoded == trimmed.rstrip("="):
                return decoded
    except (binascii.Error, ValueError):
        pass

    return trimmed.encode("utf-8")


def _require_secret(
    value: Optional[Union[str, SecretStr]], name: str
) -> bytes:
    if value is None:
        raise ConfigurationError(f"{name} is not configured")
    return _normalize_secret_value(value)


def get_jwt_secret_bytes() -> bytes:
    """Return the current HS256 secret for access tokens."""
    if settings.auth.jwt_secret:
        return _require_secret(settings.auth.jwt_secret, "AUTH_JWT_SECRET")
    if settings.secret_key:
        return _require_secret(settings.secret_key, "SECRET_KEY")
    raise ConfigurationError("AUTH_JWT_SECRET not configured")


def get_refresh_secret_bytes() -> bytes:
    """Return the secret used to hash refresh tokens."""
    if settings.auth.refresh_token_secret:
        return _require_secret(settings.auth.refresh_token_secret, "AUTH_REFRESH_TOKEN_SECRET")
    return get_jwt_secret_bytes()
